services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    Rostock\CustomElementsBundle\:
        resource: ../src
        exclude: ../src/{Classes,ContaoManager,DependencyInjection,Elements,Module,EventListener,Security}

    Rostock\CustomElementsBundle\EventListener\:
        resource: ../src/EventListener

    Rostock\CustomElementsBundle\Classes\PsaMemberFlash:
        autowire: true

    Rostock\CustomElementsBundle\Classes\PsaEventRsvp:
        autowire: true

    Rostock\CustomElementsBundle\Classes\PsaMeetup:
        autowire: true

    Rostock\CustomElementsBundle\Classes\PsaMeetupJsonPresenter:
        autowire: true

    Rostock\CustomElementsBundle\Classes\PsaTeam:
        autowire: true

    Rostock\CustomElementsBundle\Classes\PsaLookback:
        autowire: true

    contao.security.frontend_user_provider:
        class: Rostock\CustomElementsBundle\Security\PsaFrontendUserProvider
        arguments:
            - '@contao.framework'
            - 'Contao\FrontendUser'
